/*CREATED AND EDITED BY WALTER RIVERA*/

/*    REGLA GENERAL*/

/*PARA  EL NOMBRE DE LAS SECUENCIAS
VAMOS A COLOCAR SEQ_TBL_NOMBRE_TABLA*/

/*PARA EL NOMBRE DE TRIGGERS
TRIG_(BF,AF,INST)_NOMBRE_TABLA*/

/***********************************************************************************************/

/*tabla configuracion*/
/*creando la secuencia correspondiente*/
CREATE SEQUENCE SEQ_TBL_TBLCONFIG
START WITH 1
INCREMENT BY 1;
COMMIT;


CREATE OR REPLACE TRIGGER BI_TBL_TBLCONFIG
BEFORE INSERT ON TABLA_CONFIGURACION
FOR EACH ROW
BEGIN
SELECT SEQ_TBL_TBLCONFIG.NEXTVAL INTO :NEW.ID_TABLA FROM DUAL;
END BI_TBL_TBLCONFIG;




/*INSERCIÓN DE DATOS*/
INSERT INTO TABLA_CONFIGURACION(NOMBRE) VALUES('TIPO_OPERACION_EMPRESA');
INSERT INTO TABLA_CONFIGURACION(NOMBRE) VALUES('CAMPO_BITACORA_EMPRESA');
INSERT INTO TABLA_CONFIGURACION(NOMBRE) VALUES('ESTATUS_EMPRESA');
INSERT INTO TABLA_CONFIGURACION(NOMBRE) VALUES('CAMPO_BITACORA_USUARIO');
INSERT INTO TABLA_CONFIGURACION(NOMBRE) VALUES('TIPO_OPERACION_USUARIO');
INSERT INTO TABLA_CONFIGURACION(NOMBRE) VALUES('PAIS');
INSERT INTO TABLA_CONFIGURACION(NOMBRE) VALUES('TIPO_TRR_BITACORA_LIBRETA');
INSERT INTO TABLA_CONFIGURACION(NOMBRE) VALUES('ESTATUS_USUARIO');
INSERT INTO TABLA_CONFIGURACION(NOMBRE) VALUES('TIPO_GENERO');
INSERT INTO TABLA_CONFIGURACION(NOMBRE) VALUES('MODULO');
INSERT INTO TABLA_CONFIGURACION(NOMBRE) VALUES('ESTATUS_LIBRETA');
INSERT INTO TABLA_CONFIGURACION(NOMBRE) VALUES('TP_TRANSACC_BITACORA_CLIENTE');
INSERT INTO TABLA_CONFIGURACION(NOMBRE) VALUES('CAMPO_BITACORA_CLIENTE');
INSERT INTO TABLA_CONFIGURACION(NOMBRE) VALUES('TIPO_TRANSACCION_BOVEDA');
INSERT INTO TABLA_CONFIGURACION(NOMBRE) VALUES('ESTATUS_CHEQUERA');
INSERT INTO TABLA_CONFIGURACION(NOMBRE) VALUES('ESTATUS_CUENTA');
INSERT INTO TABLA_CONFIGURACION(NOMBRE) VALUES('TIPO_CUENTA');
INSERT INTO TABLA_CONFIGURACION(NOMBRE) VALUES('TIPO_BOLETA');
INSERT INTO TABLA_CONFIGURACION(NOMBRE) VALUES('ESTATUS_BOLETA');
INSERT INTO TABLA_CONFIGURACION(NOMBRE) VALUES('ESTATUS_CHEQUE');
INSERT INTO TABLA_CONFIGURACION(NOMBRE) VALUES('TIPO_TRANSACCION');
INSERT INTO TABLA_CONFIGURACION(NOMBRE) VALUES('ESTATUS_AGENCIA');
INSERT INTO TABLA_CONFIGURACION(NOMBRE) VALUES('ESTATUS_CAJA');
INSERT INTO TABLA_CONFIGURACION(NOMBRE) VALUES('TIPO_TRANSAC_BITACORA_CHEQ');
INSERT INTO TABLA_CONFIGURACION(NOMBRE) VALUES('TIPO_TRANSACCION_CAJA');
INSERT INTO TABLA_CONFIGURACION(NOMBRE) VALUES('ESTATUS_BOVEDA');
INSERT INTO TABLA_CONFIGURACION(NOMBRE) VALUES('ESTADO_TRANSACCION_GEN');
INSERT INTO TABLA_CONFIGURACION(NOMBRE) VALUES('TIPO_USUARIO');
INSERT INTO TABLA_CONFIGURACION(NOMBRE) VALUES('DEPARTAMENTO');
INSERT INTO TABLA_CONFIGURACION(NOMBRE) VALUES('MUNICIPIO');

/***********************************************************************************************/


