/*antes de tener una cuenta, debe existir un CLIENTE
por lo que procedemos a crearlo por medio de plsql*/
/*1.- creamos una secuencia para llevar el control de los correlativos EN LAS DISTINTAS TABLAS QUE TENGAN
QUE VER CON CLIENTE, EN ESTA CASO ELLA MISMA Y SU BITÁCORA*/

/*SECUENCIA PARA LE ID DE CLIENTES*/
CREATE SEQUENCE SEQ_NUMERO_CLIENTES
START WITH 1
INCREMENT BY 1;

/*SECUENCIA PARA EL ID DE LA BITACORA*/
CREATE SEQUENCE SEQ_BITACORA_CLIENTE
START WITH 1
INCREMENT BY 1; 

/*2.- debemos crear el directorio donde vamos a almacenar las firmas de los clientes*/
/*2.1 definimos el nombre del directorio y la ruta*/
CREATE OR REPLACE DIRECTORY IMAGENES AS 'C:\firmas';
/*2.2 - otorgamos los permisos a los usuarios debemos crear un rol y los permisos que tendrá a ciertas tablas*/
GRANT READ, WRITE ON DIRECTORY IMAGENES TO HR WITH GRANT OPTION; 

/*TRIGGER PARA CAMPO AUTOINCREMENTABLE*/
CREATE OR REPLACE TRIGGER BI_CLIENTE 
BEFORE INSERT ON CLIENTE
FOR EACH ROW
BEGIN
SELECT SEQ_NUMERO_CLIENTES.NEXTVAL INTO :NEW.ID_CLIENTE_NUMERO FROM DUAL;
END BI_CLIENTE;
/

/*3.- VAMOS A CREAR UN PROCEDIMIENTO ALMACENADO PARA LA INSERCIÓN DE DATOS EN LA TABLA CLIENTE,
VAMOS A MANDAR COMO PARÁMETRO UNA VARIABLE TIPO %ROWTYPE PARA HACER MAS FÁCIL EL PROCESO,
*/
CREATE OR REPLACE PROCEDURE PROC_CREAR_CLIENTE(DATOS_CLIENTE CLIENTE%ROWTYPE)
    IS
    GENERO TIPO_GENERO.TIPO_GENERO%TYPE;
    NO_EXISTE_TIPO EXCEPTION;
    NO_EXISTE_USUARIO EXCEPTION;
    ID_USUARIO_EXISTENTE NUMBER;
    /*EL USUARIO DEBE DE ESTAR ACTIVO PARA INSERTAR SI SEGÚN SU ROL TIENE ESTE PRIVILEGIO*/
    USUARIO_ACT ESTATUS_USUARIO.NOMBRE%TYPE;
    BEGIN
        /*Evaluamos SI EL TIPO DE GENERO SELECCIONADO EXISTE DENTRO DE LOS YA
        ESTABLECIDOS EN LA BASE DE DATOS*/
        SELECT COUNT(TIPO_GENERO) INTO GENERO FROM TIPO_GENERO WHERE TIPO_GENERO=DATOS_CLIENTE.TIPO_GENERO; 
        /*VERIFICAMOS CON EL USUARIO QUE SE HAYAN LOGEADO EN EL SISTEMA ESTÁ, DENTRO DE NUESTRA TABLA USUARIO DEL NEGOCIO
        Y A LA  VEZ SI ESTÁ HABILITADO*/
        SELECT ID_USUARIO INTO ID_USUARIO_EXISTENTE  FROM USUARIO WHERE NOMBRE_USUARIO=(SELECT USERNAME FROM ALL_USERS WHERE USERNAME=USER);
          /*validamos si el usuario está activo*/
        SELECT  NOMBRE  INTO USUARIO_ACT FROM ESTATUS_USUARIO ET
            INNER JOIN USUARIO USR
            ON ET.ID_ESTATUS_USUARIO=USR.ESTATUS_USUARIO
            WHERE  USR.ID_USUARIO=ID_USUARIO_EXISTENTE;
        /*SE PUDIESE SER DE OTRA FORMA MAS LIMPIA, PERO
            POR FINES DE APRENDIZAJE SE HIZO EL INNER JOIN*/
        IF(GENERO>0 AND ID_USUARIO_EXISTENTE>0 AND USUARIO_ACT='ACTIVO') THEN
            /*si todo transcurre con normalidad, insertamos datos EL ESTATUS 1 QUIERE DECIR QUE POR DEFECTO VAMOS A ACTIVAR AL CLIENTE*/
            INSERT INTO CLIENTE(NOMBRES,APELLIDOS,DPI,NIT,MUNICIPIO,DIRECCION,TELEFONO,CELULAR,CORREO_ELECTRONICO,TIPO_GENERO,FECHA_NACIMIENTO,IMAGEN_FIRMA,ID_ESTATUS_CLIENTE)
            VALUES(DATOS_CLIENTE.NOMBRES,DATOS_CLIENTE.APELLIDOS,DATOS_CLIENTE.DPI,DATOS_CLIENTE.NIT,DATOS_CLIENTE.MUNICIPIO,DATOS_CLIENTE.DIRECCION,DATOS_CLIENTE.TELEFONO,DATOS_CLIENTE.CELULAR,
            DATOS_CLIENTE.CORREO_ELECTRONICO, DATOS_CLIENTE.TIPO_GENERO,DATOS_CLIENTE.FECHA_NACIMIENTO,DATOS_CLIENTE.IMAGEN_FIRMA,1);
        /*SINO EXISTE EL TIPO LEVANTAMOS UNA EXCEPCION PROPIA*/
        ELSE
            IF(GENERO<=0) THEN
                RAISE NO_EXISTE_TIPO;
            ELSIF(ID_USUARIO_EXISTENTE<=0) THEN
                RAISE NO_EXISTE_USUARIO;
            END IF;    
        END IF;
        /*Al salir todo bien, confirmamos la transacción*/
        COMMIT;
        EXCEPTION
            WHEN NO_EXISTE_USUARIO THEN
                 DBMS_OUTPUT.PUT_LINE('EL USUARIO NO EXISTE EN LA BASE DE DATOS O NO TIENE PERMISOS');
            WHEN NO_EXISTE_TIPO THEN
                 DBMS_OUTPUT.PUT_LINE('SELECCCIONE UN GENERO CORRECTO');
            /*SI POR X O Y MOTIVO SE PLANEA INSERTAR UN USUARIO CON UN ID YA EXISTENTE*/
            WHEN DUP_VAL_ON_INDEX THEN
                 DBMS_OUTPUT.PUT_LINE('ESTÁ INTENTANDO INSERTAR UN NUMERO DE CLIENTE YA EXISTENTE, REVISE POR FAVOR, O COMUNÍQUESE CON EL DBA');
            /*Como para la inserción únicamente vamos a evaluar si el tipo de género existe,
            sino lo ecuentra devolverá esta excepción*/
            WHEN NO_DATA_FOUND THEN
                DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRÓ DATO RELACIONADO A');
            /*Se agotò el tiempo de espera*/
            WHEN TIMEOUT_ON_RESOURCE THEN
                DBMS_OUTPUT.PUT_LINE('SE AGOTÓ EL TIEMPO DE ESPERA');
            /*Se intentó hacer una operación aritmética, pero no se logro realizar*/
            WHEN VALUE_ERROR THEN
                DBMS_OUTPUT.PUT_LINE('ERROR DE ÍNDOLE ARITMÉTICO');
            /*En un parámetro que es de tipo numérico se ingresa un caracter distinto a un número*/
            WHEN INVALID_NUMBER THEN
                DBMS_OUTPUT.PUT_LINE('FALLÓ LA CONVERSIÓN DE UN STRING O CARACTER A NÚMERO');
            /*No se permitió el acceso a la base de datos*/
            WHEN LOGIN_DENIED THEN
                DBMS_OUTPUT.PUT_LINE('ERROR AL MOMENTO DE REALIZAR EL LOGIN EN LA BASE DE DATOS');
            /*Si se presenta otro tipo de error*/
            WHEN OTHERS THEN 
                DBMS_OUTPUT.PUT_LINE('OCURRIÓ UN ERROR    '||SQLCODE||'    Mensaje:    '||SQLERRM);
        /*En dado caso la transacción presenta algún problema durante su uso, la revertimos*/
        ROLLBACK;
/*FIN DEL PROCEDIMIENTO ALMACENADO*/
END PROC_CREAR_CLIENTE;
/

/* 4.- CAMPO AUTOINCREMENTABLE DE LA BITACORA DEL CLIENTE*/
CREATE OR REPLACE TRIGGER BI_BITACORA_CLIENTE 
BEFORE INSERT ON BITACORA_CLIENTE
FOR EACH ROW
BEGIN
SELECT SEQ_BITACORA_CLIENTE.NEXTVAL INTO :NEW.ID_BITACORA_CLIENTE FROM DUAL;
END BI_BITACORA_CLIENTE;
/

/* 5.- después de insertar datos en la tabla cliente debemos registrarlos en bitacora cliente (la inserción)*/
/* 5.- después de insertar datos en la tabla cliente debemos registrarlos en bitacora cliente (la inserción)*/
CREATE OR REPLACE TRIGGER AIUD_TBL_CLIENTE
AFTER INSERT OR UPDATE OR DELETE  ON CLIENTE
FOR EACH ROW
DECLARE
/*VARIABLE PARA HACER UNA VALIDACIOÓN SI EL USUARIO LOEGUEADO
 EXISTE*/
EXISTE_USUARIO NUMBER:=0;
/*EL USUARIO DEBE DE ESTAR ACTIVO PARA ACTUALIZAR ALGÚN CAMPO DE LOS QUE TIENE ACCESO SEGÚN SU ROL*/
USUARIO_ACTIVO ESTATUS_USUARIO.NOMBRE%TYPE;
/*expeciones propias*/
BEGIN
    /*Validamos que el usuario de la base de datos exista dentro nuestros registros en la tabla usuario*/
    SELECT ID_USUARIO INTO EXISTE_USUARIO FROM USUARIO WHERE NOMBRE_USUARIO=(SELECT USERNAME FROM ALL_USERS WHERE USERNAME=USER);
    /*validamos si el usuario está activo*/
    SELECT  NOMBRE  INTO USUARIO_ACTIVO FROM ESTATUS_USUARIO ET
        INNER JOIN USUARIO USR
        ON ET.ID_ESTATUS_USUARIO=USR.ESTATUS_USUARIO
        WHERE  USR.ID_USUARIO=EXISTE_USUARIO;
    /*SE PUDIESE SER DE OTRA FORMA MAS LIMPIA, PERO
        POR FINES DE APRENDIZAJE SE HIZO EL INNER JOIN*/
    IF (EXISTE_USUARIO>0  AND USUARIO_ACTIVO='ACTIVO')THEN
        /*después de insertar en la tabla cliente, insertamos en nustro log (bitacora_cliente)
        en este caso solo vamos a registrar la opeacioón como tal (inserción) ya que cuando actualice
        unta tupla completa o campo, lo vamos registrar y podremos saber el valor anterior y nuevo del campo que se afectado*/
            IF INSERTING THEN
                INSERT INTO BITACORA_CLIENTE (ID_CLIENTE,ID_USUARIO,TIPO_TRANSACCION,FECHA,ID_CAMPO_AFECTADO,VALOR_ANTIGUO,VALOR_NUEVO) 
                VALUES(:NEW.ID_CLIENTE_NUMERO,EXISTE_USUARIO,2,SYSDATE,NULL,NULL,NULL);
            END IF;   
        /*si actualiza cualquier campo del cliente (a excepción del id, pues este es autoincrentable y único)*/
            IF UPDATING ('NOMBRES') THEN
                INSERT INTO BITACORA_CLIENTE (ID_CLIENTE,ID_USUARIO,TIPO_TRANSACCION,FECHA,ID_CAMPO_AFECTADO,VALOR_ANTIGUO,VALOR_NUEVO)
                VALUES(:NEW.ID_CLIENTE_NUMERO,EXISTE_USUARIO,1,SYSDATE,2,:OLD.NOMBRES,:NEW.NOMBRES);
            END IF;
            IF UPDATING ('APELLIDOS') THEN
                INSERT INTO BITACORA_CLIENTE (ID_CLIENTE,ID_USUARIO,TIPO_TRANSACCION,FECHA,ID_CAMPO_AFECTADO,VALOR_ANTIGUO,VALOR_NUEVO)
                VALUES(:NEW.ID_CLIENTE_NUMERO,EXISTE_USUARIO,1,SYSDATE,3,:OLD.APELLIDOS,:NEW.APELLIDOS);
            END IF;
            IF UPDATING ('DPI') THEN
                INSERT INTO BITACORA_CLIENTE (ID_CLIENTE,ID_USUARIO,TIPO_TRANSACCION,FECHA,ID_CAMPO_AFECTADO,VALOR_ANTIGUO,VALOR_NUEVO)
                VALUES(:NEW.ID_CLIENTE_NUMERO,EXISTE_USUARIO,1,SYSDATE,4,:OLD.DPI,:NEW.DPI);
            END IF;
            IF UPDATING ('NIT') THEN
                INSERT INTO BITACORA_CLIENTE (ID_CLIENTE,ID_USUARIO,TIPO_TRANSACCION,FECHA,ID_CAMPO_AFECTADO,VALOR_ANTIGUO,VALOR_NUEVO)
                VALUES(:NEW.ID_CLIENTE_NUMERO,EXISTE_USUARIO,1,SYSDATE,5,:OLD.NIT,:NEW.NIT);
            END IF;
            IF UPDATING ('MUNICIPIO') THEN
                INSERT INTO BITACORA_CLIENTE (ID_CLIENTE,ID_USUARIO,TIPO_TRANSACCION,FECHA,ID_CAMPO_AFECTADO,VALOR_ANTIGUO,VALOR_NUEVO)
                VALUES(:NEW.ID_CLIENTE_NUMERO,EXISTE_USUARIO,1,SYSDATE,6,:OLD.MUNICIPIO,:NEW.MUNICIPIO);
            END IF;
            IF UPDATING ('DIRECCION') THEN
                INSERT INTO BITACORA_CLIENTE (ID_CLIENTE,ID_USUARIO,TIPO_TRANSACCION,FECHA,ID_CAMPO_AFECTADO,VALOR_ANTIGUO,VALOR_NUEVO)
                VALUES(:NEW.ID_CLIENTE_NUMERO,EXISTE_USUARIO,1,SYSDATE,7,:OLD.DIRECCION,:NEW.DIRECCION);
            END IF;
            IF UPDATING ('TELEFONO') THEN
                INSERT INTO BITACORA_CLIENTE (ID_CLIENTE,ID_USUARIO,TIPO_TRANSACCION,FECHA,ID_CAMPO_AFECTADO,VALOR_ANTIGUO,VALOR_NUEVO)
                VALUES(:NEW.ID_CLIENTE_NUMERO,EXISTE_USUARIO,1,SYSDATE,8,:OLD.TELEFONO,:NEW.TELEFONO);
            END IF;
            IF UPDATING ('CELULAR') THEN
                INSERT INTO BITACORA_CLIENTE (ID_CLIENTE,ID_USUARIO,TIPO_TRANSACCION,FECHA,ID_CAMPO_AFECTADO,VALOR_ANTIGUO,VALOR_NUEVO)
                VALUES(:NEW.ID_CLIENTE_NUMERO,EXISTE_USUARIO,1,SYSDATE,9,:OLD.CELULAR,:NEW.CELULAR);
            END IF;
            IF UPDATING ('CORREO_ELECTRONICO') THEN
                INSERT INTO BITACORA_CLIENTE (ID_CLIENTE,ID_USUARIO,TIPO_TRANSACCION,FECHA,ID_CAMPO_AFECTADO,VALOR_ANTIGUO,VALOR_NUEVO)
                VALUES(:NEW.ID_CLIENTE_NUMERO,EXISTE_USUARIO,1,SYSDATE,10,:OLD.CORREO_ELECTRONICO,:NEW.CORREO_ELECTRONICO);
            END IF;
            IF UPDATING ('TIPO_GENERO') THEN
                INSERT INTO BITACORA_CLIENTE (ID_CLIENTE,ID_USUARIO,TIPO_TRANSACCION,FECHA,ID_CAMPO_AFECTADO,VALOR_ANTIGUO,VALOR_NUEVO)
                VALUES(:NEW.ID_CLIENTE_NUMERO,EXISTE_USUARIO,1,SYSDATE,11,:OLD.TIPO_GENERO,:NEW.TIPO_GENERO);
            END IF;
            IF UPDATING ('FECHA_NACIMIENTO') THEN
                INSERT INTO BITACORA_CLIENTE (ID_CLIENTE,ID_USUARIO,TIPO_TRANSACCION,FECHA,ID_CAMPO_AFECTADO,VALOR_ANTIGUO,VALOR_NUEVO)
                VALUES(:NEW.ID_CLIENTE_NUMERO,EXISTE_USUARIO,1,SYSDATE,12,:OLD.FECHA_NACIMIENTO,:NEW.FECHA_NACIMIENTO);
            END IF;
            IF UPDATING ('IMAGEN_FIRMA') THEN
                INSERT INTO BITACORA_CLIENTE (ID_CLIENTE,ID_USUARIO,TIPO_TRANSACCION,FECHA,ID_CAMPO_AFECTADO,IMG_ANTIGUA,IMG_NUEVA)
                VALUES(:NEW.ID_CLIENTE_NUMERO,EXISTE_USUARIO,1,SYSDATE,13,:OLD.IMAGEN_FIRMA,:NEW.IMAGEN_FIRMA);
            END IF;
            IF UPDATING ('ID_ESTATUS_CLIENTE') THEN
                INSERT INTO BITACORA_CLIENTE (ID_CLIENTE,ID_USUARIO,TIPO_TRANSACCION,FECHA,ID_CAMPO_AFECTADO,VALOR_ANTIGUO,VALOR_NUEVO)
                VALUES(:NEW.ID_CLIENTE_NUMERO,EXISTE_USUARIO,1,SYSDATE,14,:OLD.ID_ESTATUS_CLIENTE,:NEW.ID_ESTATUS_CLIENTE);
            END IF;
    END IF;
    EXCEPTION
    /*si por algún motivo falla alguna conversión de un número*/
    WHEN INVALID_NUMBER THEN
        DBMS_OUTPUT.PUT_LINE(SQLCODE||'  FALLÓ LA CONVERSIÓN DE:    '||SQLERRM);
    /*si el usuario quiere insertar un valor con un id de la tabla  ya  creado*/
    WHEN DUP_VAL_ON_INDEX THEN
        DBMS_OUTPUT.PUT_LINE('ESTÁ INTENTANDO REGISTRAR CON UN ID YA EXISTENTE, COMUNIQUESE CON EL DBA');
    /*si el  usuario no está registrado dentro de la base de datos*/
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('USTED NO TIENE PRIVILEGIOS O PERMISOS PARA CREAR ESTA OPERACION, CONTACTE CON EL DBA');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE(SQLCODE||'    ERROR:     '||'MENSAJE    '||SQLERRM);
END;
/
COMMIT;

/*6.- FORMA DE MANDAR LOS DATOS PARA EL STORED PROCEDURE*/
/*BLOQUE ANÒNIMO*/

DECLARE 
CLIENTE_N CLIENTE%ROWTYPE;
BEGIN
CLIENTE_N.NOMBRES:='WALTER GIOVANNI';
CLIENTE_N.APELLIDOS:='RIVERA LÓPEZ';
CLIENTE_N.DPI:='265609010101';
CLIENTE_N.NIT:='8659552-0';
CLIENTE_N.MUNICIPIO:=1;
CLIENTE_N.DIRECCION:='AV. EL CEMENTERIO 18-26 ZONA 3, GUATEMALA, GUATEMALA';
CLIENTE_N.TELEFONO:='44533196';
CLIENTE_N.CELULAR:='';
CLIENTE_N.CORREO_ELECTRONICO:='walterej@hotmail.es';
CLIENTE_N.TIPO_GENERO:=1;
CLIENTE_N.FECHA_NACIMIENTO:=TO_DATE('20/11/1994','dd/mm/yyyy');
CLIENTE_N.IMAGEN_FIRMA:=NULL;
/*PROBAMOS EL PROCEDIMIENTO ALMACENADO*/
PROC_CREAR_CLIENTE(CLIENTE_N);
END;
/

/*para saber que triggers tiene una tabla*/
SELECT   *
  FROM   user_triggers
WHERE   table_name = 'CLIENTE' 
   AND   trigger_type LIKE '%EACH ROW'


/*hasta acá termina lo relacionado con el cliente (lógica del negocio)*


/*---------------------------------------------xxxxxxxxxxxxxxxxxxxx-------------------------------------*/

                                                   /*USUARIO*/
/*----------------------------------------------xxxxxxxxxxxxxxxxxxx--------------------------------------*/
/*antes de tener una cuenta, debe existir un USUARIO
por lo que procedemos a crearlo por medio de plsql*/
/*1.- creamos una secuencia para llevar el control de los correlativos EN LAS DISTINTAS TABLAS QUE TENGAN
QUE VER CON USUARIO, EN ESTA CASO ELLA MISMA Y SU BITÁCORA*/

/*SECUENCIA PARA LE ID DE USUARIOS*/
CREATE SEQUENCE SEQ_NUMERO_USUARIO
START WITH 1
INCREMENT BY 1;
COMMIT;
/
/*SECUENCIA PARA EL ID DE LA BITACORA*/
CREATE SEQUENCE SEQ_BITACORA_USUARIO
START WITH 1
INCREMENT BY 1; 
COMMIT;
/
/*2.- debemos crear el directorio donde vamos a almacenar las firmas de los USUARIOs*/
/*2.1 definimos el nombre del directorio y la ruta*/
CREATE OR REPLACE DIRECTORY DIR_USUARIO AS 'C:\USUARIO_FOTOGRAFIA';
/*2.2 - otorgamos los permisos a los usuarios debemos crear un rol y los permisos que tendrá a ciertas tablas*/
GRANT READ, WRITE ON DIRECTORY DIR_USUARIO TO HR WITH GRANT OPTION; 
COMMIT;

/*TRIGGER PARA CAMPO AUTOINCREMENTABLE*/
CREATE OR REPLACE TRIGGER BI_USUARIO 
BEFORE INSERT ON USUARIO
FOR EACH ROW
BEGIN
SELECT SEQ_BITACORA_USUARIO.NEXTVAL INTO :NEW.ID_USUARIO FROM DUAL;
END BI_USUARIO;
COMMIT;
/

/*3.- VAMOS A CREAR UN PROCEDIMIENTO ALMACENADO PARA LA INSERCIÓN DE DATOS EN LA TABLA USUARIO,
VAMOS A MANDAR COMO PARÁMETRO UNA VARIABLE TIPO %ROWTYPE PARA HACER MAS FÁCIL EL PROCESO,
*/
CREATE OR REPLACE PROCEDURE PROC_CREAR_USUARIO(DATOS_USUARIO USUARIO%ROWTYPE)
    IS
    GENERO TIPO_GENERO.TIPO_GENERO%TYPE;
    NO_EXIST_TIPO EXCEPTION;
    NO_EXIST_USR EXCEPTION;
    EXISTE_USUARIO NUMBER;
    /*EL USUARIO DEBE DE ESTAR ACTIVO PARA INSERTAR SI SEGÚN SU ROL TIENE ESTE PRIVILEGIO*/
    USUARIO_ACT ESTATUS_USUARIO.NOMBRE%TYPE;
    BEGIN
        /*reviso en la base de datos, si el usuario ya está creado en la misma, esto con el fin de aprendizaje
        se requiere que para crear un usuario en nuestro sistema, debe estar previamente creado en la base de datos
        a nivel del dba*/
         SELECT COUNT(*) INTO EXISTE_USUARIO FROM ALL_USERS WHERE USERNAME=DATOS_USUARIO.NOMBRE_USUARIO;

        /*Evaluamos SI EL TIPO DE GENERO SELECCIONADO EXISTE DENTRO DE LOS YA
        ESTABLECIDOS EN LA BASE DE DATOS*/
        SELECT COUNT(TIPO_GENERO) INTO GENERO FROM TIPO_GENERO WHERE TIPO_GENERO=DATOS_USUARIO.TIPO_GENERO; 
        /**/
        IF(GENERO>0 AND EXISTE_USUARIO>0) THEN
            /*si todo transcurre con normalidad, insertamos datos EL ESTATUS 1 QUIERE DECIR QUE POR DEFECTO VAMOS A ACTIVAR AL USUARIO*/
            INSERT INTO USUARIO(NOMBRE_USUARIO,NOMBRES,APELLIDOS,DPI,DIRECCION,CORREO_ELECTRONICO,TELEFONO,CELULAR,FECHA_NACIMIENTO,
            FECHA_CREACION, FOTOGRAFIA, CONTRASENA,ID_AGENCIA,ID_MUNICIPIO,TIPO_USUARIO,TIPO_GENERO,ESTATUS_USUARIO)

            VALUES(DATOS_USUARIO.NOMBRE_USUARIO, DATOS_USUARIO.NOMBRES, DATOS_USUARIO.APELLIDOS, DATOS_USUARIO.DPI, DATOS_USUARIO.DIRECCION,
            DATOS_USUARIO.CORREO_ELECTRONICO, DATOS_USUARIO.TELEFONO, DATOS_USUARIO.CELULAR, DATOS_USUARIO.FECHA_NACIMIENTO, SYSDATE,
            DATOS_USUARIO.FOTOGRAFIA, DATOS_USUARIO.CONTRASENA, DATOS_USUARIO.ID_AGENCIA, DATOS_USUARIO.ID_MUNICIPIO, 
            DATOS_USUARIO.TIPO_USUARIO, DATOS_USUARIO.TIPO_GENERO,1);
        /*SINO EXISTE EL TIPO LEVANTAMOS UNA EXCEPCION PROPIA*/
        ELSE
            IF(GENERO=0) THEN
                RAISE NO_EXIST_TIPO;
            ELSIF(EXISTE_USUARIO<=0) THEN
                RAISE NO_EXIST_USR;
            END IF;    
        END IF;
        /*Al salir todo bien, confirmamos la transacción*/
        COMMIT;
        EXCEPTION
            WHEN NO_EXIST_USR THEN
                 DBMS_OUTPUT.PUT_LINE('EL USUARIO NO EXISTE EN LA BASE DE DATOS O NO TIENE PERMISOS');
            WHEN NO_EXIST_TIPO THEN
                 DBMS_OUTPUT.PUT_LINE('SELECCCIONE UN GENERO CORRECTO');
            /*SI POR X O Y MOTIVO SE PLANEA INSERTAR UN USUARIO CON UN ID YA EXISTENTE*/
            WHEN DUP_VAL_ON_INDEX THEN
                 DBMS_OUTPUT.PUT_LINE('ESTÁ INTENTANDO INSERTAR UN NUMERO DE USUARIO YA EXISTENTE, REVISE POR FAVOR, O COMUNÍQUESE CON EL DBA');
            /*Como para la inserción únicamente vamos a evaluar si el tipo de género existe,
            sino lo ecuentra devolverá esta excepción*/
            WHEN NO_DATA_FOUND THEN
                DBMS_OUTPUT.PUT_LINE('NO SE ENCONTRÓ DATO RELACIONADO A');
            /*Se agotò el tiempo de espera*/
            WHEN TIMEOUT_ON_RESOURCE THEN
                DBMS_OUTPUT.PUT_LINE('SE AGOTÓ EL TIEMPO DE ESPERA');
            /*Se intentó hacer una operación aritmética, pero no se logro realizar*/
            WHEN VALUE_ERROR THEN
                DBMS_OUTPUT.PUT_LINE('ERROR DE ÍNDOLE ARITMÉTICO');
            /*En un parámetro que es de tipo numérico se ingresa un caracter distinto a un número*/
            WHEN INVALID_NUMBER THEN
                DBMS_OUTPUT.PUT_LINE('FALLÓ LA CONVERSIÓN DE UN STRING O CARACTER A NÚMERO');
            /*No se permitió el acceso a la base de datos*/
            WHEN LOGIN_DENIED THEN
                DBMS_OUTPUT.PUT_LINE('ERROR AL MOMENTO DE REALIZAR EL LOGIN EN LA BASE DE DATOS');
            /*Si se presenta otro tipo de error*/
            WHEN OTHERS THEN 
                DBMS_OUTPUT.PUT_LINE('OCURRIÓ UN ERROR    '||SQLCODE||'    Mensaje:    '||SQLERRM);
        /*En dado caso la transacción presenta algún problema durante su uso, la revertimos*/
        ROLLBACK;
/*FIN DEL PROCEDIMIENTO ALMACENADO*/
END PROC_CREAR_USUARIO;
/

/* 4.- CAMPO AUTOINCREMENTABLE DE LA BITACORA DEL USUARIO*/
CREATE OR REPLACE TRIGGER BI_BITACORA_USUARIO 
BEFORE INSERT ON BITACORA_USUARIO
FOR EACH ROW
BEGIN
SELECT SEQ_BITACORA_USUARIO.NEXTVAL INTO :NEW.ID_OPERACION FROM DUAL;
END BI_BITACORA_USUARIO;
/

/* 5.- después de insertar datos en la tabla USUARIO debemos registrarlos en bitacora USUARIO (la inserción)*/
CREATE OR REPLACE TRIGGER AIUD_TBL_USUARIO
AFTER INSERT OR UPDATE OR DELETE  ON USUARIO
FOR EACH ROW
DECLARE
BEGIN
    CASE WHEN INSERTING THEN
            INSERT INTO BITACORA_USUARIO (ID_USUARIO,VALOR_ANTERIOR,VALOR_NUEVO,FECHA_OPERACION,DETALLES,CAMPO_AFECTADO,TIPO_OPERACION) 
            VALUES(:NEW.ID_USUARIO,NULL,NULL,SYSDATE,'',NULL,2);

        WHEN UPDATING ('NOMBRE_USUARIO') THEN
            INSERT INTO BITACORA_USUARIO (ID_USUARIO,VALOR_ANTERIOR,VALOR_NUEVO,FECHA_OPERACION,DETALLES,CAMPO_AFECTADO,TIPO_OPERACION) 
            VALUES(:OLD.ID_USUARIO,:OLD.NOMBRE_USUARIO,:NEW.NOMBRE_USUARIO,SYSDATE,'',2,1);  
        WHEN UPDATING ('NOMBRES') THEN
            INSERT INTO BITACORA_USUARIO (ID_USUARIO,VALOR_ANTERIOR,VALOR_NUEVO,FECHA_OPERACION,DETALLES,CAMPO_AFECTADO,TIPO_OPERACION) 
            VALUES(:OLD.ID_USUARIO,:OLD.NOMBRES,:NEW.NOMBRES,SYSDATE,'',3,1);
        WHEN UPDATING ('APELLIDOS') THEN
            INSERT INTO BITACORA_USUARIO (ID_USUARIO,VALOR_ANTERIOR,VALOR_NUEVO,FECHA_OPERACION,DETALLES,CAMPO_AFECTADO,TIPO_OPERACION) 
            VALUES(:OLD.ID_USUARIO,:OLD.APELLIDOS,:NEW.APELLIDOS,SYSDATE,'',4,1);
        WHEN UPDATING ('DPI') THEN
            INSERT INTO BITACORA_USUARIO (ID_USUARIO,VALOR_ANTERIOR,VALOR_NUEVO,FECHA_OPERACION,DETALLES,CAMPO_AFECTADO,TIPO_OPERACION) 
            VALUES(:OLD.ID_USUARIO,:OLD.DPI,:NEW.DPI,SYSDATE,'',5,1);
         WHEN UPDATING ('DIRECCION') THEN
            INSERT INTO BITACORA_USUARIO (ID_USUARIO,VALOR_ANTERIOR,VALOR_NUEVO,FECHA_OPERACION,DETALLES,CAMPO_AFECTADO,TIPO_OPERACION) 
            VALUES(:OLD.ID_USUARIO,:OLD.DIRECCION,:NEW.DIRECCION,SYSDATE,'',6,1); 
         WHEN UPDATING ('CORREO_ELECTRONICO') THEN
            INSERT INTO BITACORA_USUARIO (ID_USUARIO,VALOR_ANTERIOR,VALOR_NUEVO,FECHA_OPERACION,DETALLES,CAMPO_AFECTADO,TIPO_OPERACION) 
            VALUES(:OLD.ID_USUARIO,:OLD.CORREO_ELECTRONICO,:NEW.CORREO_ELECTRONICO,SYSDATE,'',7,1); 
         WHEN UPDATING ('TELEFONO') THEN
            INSERT INTO BITACORA_USUARIO (ID_USUARIO,VALOR_ANTERIOR,VALOR_NUEVO,FECHA_OPERACION,DETALLES,CAMPO_AFECTADO,TIPO_OPERACION) 
            VALUES(:OLD.ID_USUARIO,:OLD.TELEFONO,:NEW.TELEFONO,SYSDATE,'',8,1);   
         WHEN UPDATING ('CELULAR') THEN
            INSERT INTO BITACORA_USUARIO (ID_USUARIO,VALOR_ANTERIOR,VALOR_NUEVO,FECHA_OPERACION,DETALLES,CAMPO_AFECTADO,TIPO_OPERACION) 
            VALUES(:OLD.ID_USUARIO,:OLD.CELULAR,:NEW.CELULAR,SYSDATE,'',9,1); 
         WHEN UPDATING ('FECHA_NACIMIENTO') THEN
            INSERT INTO BITACORA_USUARIO (ID_USUARIO,VALOR_ANTERIOR,VALOR_NUEVO,FECHA_OPERACION,DETALLES,CAMPO_AFECTADO,TIPO_OPERACION) 
            VALUES(:OLD.ID_USUARIO,TO_CHAR(:OLD.FECHA_NACIMIENTO),TO_CHAR(:NEW.FECHA_NACIMIENTO),SYSDATE,'',10,1);
         WHEN UPDATING ('FOTOGRAFIA') THEN
            INSERT INTO BITACORA_USUARIO (ID_USUARIO,FECHA_OPERACION,DETALLES,CAMPO_AFECTADO,TIPO_OPERACION,IMG_ANTIGUA,IMG_NUEVA) 
            VALUES(:OLD.ID_USUARIO,SYSDATE,'',12,1,:OLD.FOTOGRAFIA, :NEW.FOTOGRAFIA);
         WHEN UPDATING ('CONTRASENA') THEN
            INSERT INTO BITACORA_USUARIO (ID_USUARIO,VALOR_ANTERIOR,VALOR_NUEVO,FECHA_OPERACION,DETALLES,CAMPO_AFECTADO,TIPO_OPERACION) 
            VALUES(:OLD.ID_USUARIO,:OLD.CONTRASENA,:NEW.CONTRASENA,SYSDATE,'',14,1); 
         WHEN UPDATING ('ID_AGENCIA') THEN
            INSERT INTO BITACORA_USUARIO (ID_USUARIO,VALOR_ANTERIOR,VALOR_NUEVO,FECHA_OPERACION,DETALLES,CAMPO_AFECTADO,TIPO_OPERACION) 
            VALUES(:OLD.ID_USUARIO,:OLD.ID_AGENCIA,:NEW.ID_AGENCIA,SYSDATE,'',15,1); 
        WHEN UPDATING ('ID_MUNICIPIO') THEN
            INSERT INTO BITACORA_USUARIO (ID_USUARIO,VALOR_ANTERIOR,VALOR_NUEVO,FECHA_OPERACION,DETALLES,CAMPO_AFECTADO,TIPO_OPERACION) 
            VALUES(:OLD.ID_USUARIO,:OLD.ID_MUNICIPIO,:NEW.ID_MUNICIPIO,SYSDATE,'',16,1);
        WHEN UPDATING ('TIPO_USUARIO') THEN
            INSERT INTO BITACORA_USUARIO (ID_USUARIO,VALOR_ANTERIOR,VALOR_NUEVO,FECHA_OPERACION,DETALLES,CAMPO_AFECTADO,TIPO_OPERACION) 
            VALUES(:OLD.ID_USUARIO,:OLD.TIPO_USUARIO,:NEW.TIPO_USUARIO,SYSDATE,'',17,1);
        WHEN UPDATING ('TIPO_GENERO') THEN
            INSERT INTO BITACORA_USUARIO (ID_USUARIO,VALOR_ANTERIOR,VALOR_NUEVO,FECHA_OPERACION,DETALLES,CAMPO_AFECTADO,TIPO_OPERACION) 
            VALUES(:OLD.ID_USUARIO,:OLD.TIPO_GENERO,:NEW.TIPO_GENERO,SYSDATE,'',18,1);
        WHEN UPDATING ('ESTATUS_USUARIO') THEN
            INSERT INTO BITACORA_USUARIO (ID_USUARIO,VALOR_ANTERIOR,VALOR_NUEVO,FECHA_OPERACION,DETALLES,CAMPO_AFECTADO,TIPO_OPERACION) 
            VALUES(:OLD.ID_USUARIO,:OLD.ESTATUS_USUARIO,:NEW.ESTATUS_USUARIO,SYSDATE,'',19,1);    
    END CASE;         
    EXCEPTION
    /*si por algún motivo falla alguna conversión de un número*/
    WHEN INVALID_NUMBER THEN
        DBMS_OUTPUT.PUT_LINE(SQLCODE||'  FALLÓ LA CONVERSIÓN DE:    '||SQLERRM);
    /*si el usuario quiere insertar un valor con un id de la tabla  ya  creado*/
    WHEN DUP_VAL_ON_INDEX THEN
        DBMS_OUTPUT.PUT_LINE('ESTÁ INTENTANDO REGISTRAR CON UN ID YA EXISTENTE, COMUNIQUESE CON EL DBA');
    /*si el  usuario no está registrado dentro de la base de datos*/
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('USTED NO TIENE PRIVILEGIOS O PERMISOS PARA CREAR ESTA OPERACION, CONTACTE CON EL DBA');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE(SQLCODE||'    ERROR:     '||'MENSAJE    '||SQLERRM);
END;
/
COMMIT;
/
/*6.- FORMA DE MANDAR LOS DATOS PARA EL STORED PROCEDURE*/
/*BLOQUE ANÒNIMO*/

DECLARE
USUARIO_N USUARIO%ROWTYPE;
BEGIN

    USUARIO_N.NOMBRE_USUARIO:'HR';
    USUARIO_N.NOMBRES:='Thaner Berenice';
    USUARIO_N.APELLIDOS:='Roman';
    USUARIO_N.DPI:='2433453126483';
    USUARIO_N.DIRECCION:='zona X';
    USUARIO_N.CORREO_ELECTRONICO:='Troman@hotmail.es';
    USUARIO_N.TELEFONO:='14537154';
    USUARIO_N.CELULAR:='';
    USUARIO_N.FECHA_NACIMIENTO:=TO_DATE('02/11/1995','dd/mm/yyyy');
    USUARIO_N.FOTOGRAFIA:=NULL;
    USUARIO_N.CONTRASENA:='AJSDLFK'
    ID_AGENCIA=1;
    ID_MUNICIPIO=1;
    TIPO_USUARIO=NULL;
    TIPO_GENERO=2;
END;
/*PROBAMOS EL PROCEDIMIENTO ALMACENADO*/
PROC_CREAR_USUARIO(USUARIO_N);
END;
/









































/*CAMPO_BITACORA_CLIENTE: ESTA TABLA TIENE LOS ID DE LOS CAMPOS QUE FUERON AFECTADOS*/
/*TP_TRANSACC_BITACORA_CLIENTE 
1- MODIFICACION
2- INSERCION
3.- BAJA */







Funcion asignar tipo de cuenta
    si es ahorro = 1
    si es monetaria = 2

si es menor a 10
    agregar "00"||numero
si es menor a 100 y mayor o igual a 10
    agregar "0"||numero
sie es mayor o igual a 100 y menor a 1000
    numero

else
    numero agencia superado


crear secuencia para campo autoincrementable

numero_aleatorio


/*NUMERO DE AGENCIA*/
DECLARE
X VARCHAR2(8):='00001';
Y NUMBER(8);
BEGIN
Y:=TO_NUMBER(X);

DBMS_OUTPUT.PUT_lINE(Y);
END;

/*NUMERO ALEATORIO*/
BEGIN 
DBMS_OUTPUT.PUT_LINE(ROUND(DBMS_RANDOM.VALUE(0,9)));
END;


/*vamos a crear 2 secuencias,
una para que lleve el control de los ID DE cuentas monetarias y otro 
para cuentas de ahorro*/
/*SECUENCIA PARA LLEVAR EL CONTROL DE LOS ID_DE CUENTAS MONETARIAS*/
CREATE SEQUENCE ID_CUENTA_MONETARIA
START WITH 1
INCREMENT BY 1;

/*SECUENCIA PARA LLEVAR EL CONTROL DE LOS ID DE LAS CUENTAS DE AHORRO*/
CREATE SEQUENCE ID_CUENTA_AHORRO
START WITH 1
INCREMENT BY 1;

select * from agencia;



CREATE OR REPLACE PROCEDURE CREAR_CUENTA(TIPO_CUENTA VARCHAR2,AGENCIA NUMBER)
IS
ESTADO_CUENTA NUMBER;

BEGIN




END/;






