CREATE TABLE CLIENTE(
ID_CLIENTE NUMBER(15),
NOMBRES VARCHAR2(80),
APELLIDOS VARCHAR2(80),
NIT VARCHAR2(10),
FECHA_CREACION TIMESTAMP,
TELEFONO VARCHAR2(20),
DIRECCION VARCHAR2(200)
);
ALTER TABLE CLIENTE ADD CONSTRAINT PK_ID_CLIE PRIMARY KEY(NIT);


CREATE TABLE TIPO_ESTADO_PEDIDO(
ID_ESTADO_PEDIDO NUMBER(3),
DESCRIPCION VARCHAR2(100)
);
ALTER TABLE TIPO_ESTADO_PEDIDO ADD CONSTRAINT PK_ID_ST_PE PRIMARY KEY(ID_ESTADO_PEDIDO);


CREATE TABLE PEDIDO_VENTA(
COD_PEDIDO NUMBER(15),
NIT VARCHAR2(10),
ID_ESTADO_PEDIDO NUMBER(3),
USUARIO_RESPONSABLE NUMBER(6),
FECHA_EMISION TIMESTAMP
);
ALTER TABLE PEDIDO_VENTA ADD CONSTRAINT PK_PED_VENT PRIMARY KEY(COD_PEDIDO);
ALTER TABLE PEDIDO_VENTA ADD CONSTRAINT FK_ID_CLIE FOREIGN KEY (NIT) 
REFERENCES CLIENTE(NIT);
ALTER TABLE PEDIDO_VENTA ADD CONSTRAINT FK_ID_STATUSP FOREIGN KEY(ID_ESTADO_PEDIDO)
REFERENCES TIPO_ESTADO_PEDIDO(ID_ESTADO_PEDIDO);



CREATE TABLE TIPO_ESTADO_PRODUCTO(
ID_ESTADO_PRODUCTO NUMBER(3),
DESCRIPCION VARCHAR2(100)
);
ALTER TABLE TIPO_ESTADO_PRODUCTO ADD CONSTRAINT PK_TP_ST_PRODU PRIMARY KEY(ID_ESTADO_PRODUCTO);


CREATE TABLE TIPO_PRODUCTO(
ID_TIPO_PRODUCTO NUMBER(3),
DESCRIPCION VARCHAR2(100)
);
ALTER TABLE TIPO_PRODUCTO ADD CONSTRAINT PK_TP_PRODUC PRIMARY KEY(ID_TIPO_PRODUCTO);



CREATE TABLE PRODUCTO (
COD_PRODUCTO NUMBER(15),
NOMBRE VARCHAR2(200),
DESCRIPCION VARCHAR2(1000),
ID_ESTADO_PRODUCTO NUMBER(3),
ID_TIPO_PRODUCTO NUMBER(3),
PRECIO_COMPRA NUMBER(6,2),
PRECIO_VENTA NUMBER(6,2),
GANANCIA NUMBER(6,2),
STOCK_MAXIMO NUMBER(6),
STOCK_MINIMO NUMBER(6),
EXISTENCIA NUMBER(6),
IMG_PRODUCTO BLOB
);
ALTER TABLE PRODUCTO ADD CONSTRAINT PK_ID_PROD1 PRIMARY KEY(COD_PRODUCTO);
ALTER TABLE PRODUCTO ADD CONSTRAINT FK_ID_STPRO FOREIGN KEY(ID_ESTADO_PRODUCTO)
REFERENCES TIPO_ESTADO_PRODUCTO (ID_ESTADO_PRODUCTO);
ALTER TABLE PRODUCTO ADD CONSTRAINT FK_ID_TPPRO FOREIGN KEY(ID_TIPO_PRODUCTO)
REFERENCES TIPO_PRODUCTO(ID_TIPO_PRODUCTO);


CREATE TABLE DETALLE_PEDIDO
(
    COD_PEDIDO NUMBER(15),
    COD_PRODUCTO NUMBER(15),
    CANTIDAD_PROD NUMBER(7),
    MONTO_PARCIAL NUMBER(6,2),
    MONTO_TOTAL NUMBER(6,2)
);

ALTER TABLE DETALLE_PEDIDO ADD CONSTRAINT PK_ID_DET_PEDIDO PRIMARY KEY(COD_PEDIDO,COD_PRODUCTO); 
ALTER TABLE DETALLE_PEDIDO ADD CONSTRAINT FK_ID_PE FOREIGN KEY(COD_PEDIDO)
REFERENCES PEDIDO_VENTA(COD_PEDIDO);
ALTER TABLE DETALLE_PEDIDO ADD CONSTRAINT FK_ID_PRVENTA FOREIGN KEY(COD_PRODUCTO)
REFERENCES PRODUCTO(COD_PRODUCTO);


CREATE TABLE CAMPO_AFECTADO_PRODUCTO
(
    ID_CAMPO_AFECTADO NUMBER(3),
    DESCRIPCION VARCHAR2(80)
);
ALTER TABLE CAMPO_AFECTADO_PRODUCTO ADD CONSTRAINT PK_CMP_AF_PRO PRIMARY KEY(ID_CAMPO_AFECTADO);


CREATE TABLE TIPO_TRANSACCION_PRODUCTO
(
    COD_TIPO_TRANSACCION NUMBER(3),
    DESCRIPCION VARCHAR2(80)
);
ALTER TABLE TIPO_TRANSACCION_PRODUCTO ADD CONSTRAINT PK_CO_TRA PRIMARY KEY(COD_TIPO_TRANSACCION);



CREATE TABLE BITACORA_PRODUCTO(
COD_TRANSACCION NUMBER(15),
COD_PRODUCTO NUMBER(15),
FECHA_MOVIMIENTO TIMESTAMP,
VALOR_ANTERIOR VARCHAR2(400),
VALOR_NUEVO VARCHAR2(400),
USUARIO_RESPONSABLE NUMBER(3),
ID_CAMPO_AFECTADO NUMBER(3),
COD_TIPO_TRANSACCION NUMBER(3)
);
ALTER TABLE BITACORA_PRODUCTO ADD CONSTRAINT PK_CO_TRANSAC PRIMARY KEY(COD_TRANSACCION);
ALTER TABLE BITACORA_PRODUCTO ADD CONSTRAINT FK_COD_PROTR FOREIGN KEY(COD_PRODUCTO)
REFERENCES PRODUCTO (COD_PRODUCTO);
ALTER TABLE BITACORA_PRODUCTO ADD CONSTRAINT FK_CMP_AFECT FOREIGN KEY(ID_CAMPO_AFECTADO)
REFERENCES CAMPO_AFECTADO_PRODUCTO(ID_CAMPO_AFECTADO);

ALTER TABLE BITACORA_PRODUCTO ADD CANTIDAD_PRODUCTO NUMBER(9);


/*CREACION PARA CAMPOS AUTOINCREMENTABLES */
/*------------------------------------------------------------------------------------------------------------------*/
COMMIT;
/*DROP TABLE CLIENTE;*/

CREATE SEQUENCE SEQ_ID_CLIENTE
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER BI_CLIENTE
BEFORE INSERT ON CLIENTE
FOR EACH ROW
BEGIN
SELECT SEQ_ID_CLIENTE.NEXTVAL INTO :NEW.ID_CLIENTE FROM DUAL;
END;


/*DROP TABLE TIPO_ESTADO_PEDIDO;*/
CREATE SEQUENCE SEQ_ESTADO_PEDIDO
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER BI_ESTADO_PEDIDO
BEFORE INSERT ON TIPO_ESTADO_PEDIDO
FOR EACH ROW
BEGIN
SELECT SEQ_ESTADO_PEDIDO.NEXTVAL INTO :NEW.ID_ESTADO_PEDIDO FROM DUAL;
END;

/*DROP TABLE TIPO_ESTADO_PRODUCTO;*/
CREATE SEQUENCE SEQ_ESTADO_PRODUCTO
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER BI_ESTADO_PRODUCTO
BEFORE INSERT ON TIPO_ESTADO_PRODUCTO
FOR EACH ROW
BEGIN
SELECT SEQ_ESTADO_PRODUCTO.NEXTVAL INTO :NEW.ID_ESTADO_PRODUCTO FROM DUAL;
END;


/*DROP TABLE TIPO_PRODUCTO;*/
CREATE SEQUENCE SEQ_TIPO_PRODUCTO
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER BI_TIPO_PRODUCTO
BEFORE INSERT ON TIPO_PRODUCTO
FOR EACH ROW
BEGIN
SELECT SEQ_TIPO_PRODUCTO.NEXTVAL INTO :NEW.ID_TIPO_PRODUCTO FROM DUAL;
END;



/*DROP TABLE PRODUCTO;*/
CREATE SEQUENCE SEQ_ID_PRODUCTO
START WITH 1
INCREMENT BY 1;

create or replace TRIGGER BI_PRODUCTO
BEFORE INSERT ON PRODUCTO
FOR EACH ROW
BEGIN
IF(:NEW.PRECIO_VENTA>=:NEW.PRECIO_COMPRA) THEN
    :NEW.GANANCIA:=:NEW.PRECIO_VENTA-:NEW.PRECIO_COMPRA;
SELECT SEQ_ID_PRODUCTO.NEXTVAL INTO :NEW.COD_PRODUCTO FROM DUAL;

ELSE
    RAISE_APPLICATION_ERROR(-20001,'NO SE PUEDE RECIBIR LA MERCADERÍA, PORQUE
    NO ESTÁ GENERANDO GANANCIA');
END IF;
END;

/*DROP TABLE CAMPO_AFECTADO_PRODUCTO;*/
CREATE SEQUENCE SEQ_CAMPO_AFECTPROD
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER BI_CMP_AFECTPROD
BEFORE INSERT ON CAMPO_AFECTADO_PRODUCTO
FOR EACH ROW
BEGIN
SELECT SEQ_CAMPO_AFECTPROD.NEXTVAL INTO :NEW.ID_CAMPO_AFECTADO FROM DUAL;
END;

/*DROP TABLE TIPO_TRANSACCION_PRODUCTO;*/
CREATE SEQUENCE SEQ_TP_TRANSACCIONP
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER BI_TP_TRANSACCPROD
BEFORE INSERT ON TIPO_TRANSACCION_PRODUCTO
FOR EACH ROW
BEGIN
SELECT SEQ_TP_TRANSACCIONP.NEXTVAL INTO :NEW.COD_TIPO_TRANSACCION FROM DUAL;
END;

/*DROP TABLE BITACORA_PRODUCTO;*/
CREATE SEQUENCE SEQ_BITACORA_PRODUCTO
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER BI_BIT_PRODUCTO
BEFORE INSERT ON BITACORA_PRODUCTO
FOR EACH ROW
BEGIN
SELECT SEQ_BITACORA_PRODUCTO.NEXTVAL INTO :NEW.COD_TRANSACCION FROM DUAL;
END;

/*DROP TABLE PEDIDO_VENTA;*/
CREATE SEQUENCE SEQ_PEDIDO_VENTA
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER BI_PEDIDO_VENTA
BEFORE INSERT ON PEDIDO_VENTA
FOR EACH ROW
BEGIN
SELECT SEQ_PEDIDO_VENTA.NEXTVAL INTO :NEW.COD_PEDIDO FROM DUAL;
END;
/
COMMIT;
/



/*---------------------------------------------------------------------------------------------*/
/*INSERTS EN TABLAS*/


/*TABLA CLIENTE*/
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION)
VALUES('CLIENTE1','CONSUMIDOR1','12345678-0',SYSDATE,'','DIRECCION1');

INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION)
VALUES('CLIENTE2','CONSUMIDOR2','12345678-1',SYSDATE,'','DIRECCION2');

INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION)
VALUES('CLIENTE3','CONSUMIDOR3','12345678-2',SYSDATE,'','DIRECCION3');

INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION)
VALUES('CLIENTE4','CONSUMIDOR4','12345678-3',SYSDATE,'','DIRECCION4');

INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION)
VALUES('CLIENTE5','CONSUMIDOR5','12345678-4',SYSDATE,'','DIRECCION5');

INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION)
VALUES('CLIENTE6','CONSUMIDOR6','12345678-5',SYSDATE,'','DIRECCION6');

INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION)
VALUES('CLIENTE7','CONSUMIDOR7','12345678-6',SYSDATE,'','DIRECCION7');

INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION)
VALUES('CLIENTE8','CONSUMIDOR8','12345678-7',SYSDATE,'','DIRECCION8');

INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION)
VALUES('CLIENTE9','CONSUMIDOR9','12345678-8',SYSDATE,'','DIRECCION9');

INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION)
VALUES('CLIENTE10','CONSUMIDOR10','12345678-9',SYSDATE,'','DIRECCION10');

INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE11','CONSUMIDOR11','1-1',SYSDATE,'1000','DIRECCION11');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE12','CONSUMIDOR12','1-2',SYSDATE,'1001','DIRECCION12');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE13','CONSUMIDOR13','1-3',SYSDATE,'1002','DIRECCION13');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE14','CONSUMIDOR14','1-4',SYSDATE,'1003','DIRECCION14');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE15','CONSUMIDOR15','1-5',SYSDATE,'1004','DIRECCION15');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE16','CONSUMIDOR16','1-6',SYSDATE,'1005','DIRECCION16');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE17','CONSUMIDOR17','1-7',SYSDATE,'1006','DIRECCION17');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE18','CONSUMIDOR18','1-8',SYSDATE,'1007','DIRECCION18');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE19','CONSUMIDOR19','1-9',SYSDATE,'1008','DIRECCION19');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE20','CONSUMIDOR20','1-10',SYSDATE,'1009','DIRECCION20');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE21','CONSUMIDOR21','1-11',SYSDATE,'1010','DIRECCION21');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE22','CONSUMIDOR22','1-12',SYSDATE,'1011','DIRECCION22');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE23','CONSUMIDOR23','1-13',SYSDATE,'1012','DIRECCION23');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE24','CONSUMIDOR24','1-14',SYSDATE,'1013','DIRECCION24');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE25','CONSUMIDOR25','1-15',SYSDATE,'1014','DIRECCION25');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE26','CONSUMIDOR26','1-16',SYSDATE,'1015','DIRECCION26');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE27','CONSUMIDOR27','1-17',SYSDATE,'1016','DIRECCION27');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE28','CONSUMIDOR28','1-18',SYSDATE,'1017','DIRECCION28');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE29','CONSUMIDOR29','1-19',SYSDATE,'1018','DIRECCION29');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE30','CONSUMIDOR30','1-20',SYSDATE,'1019','DIRECCION30');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE31','CONSUMIDOR31','1-21',SYSDATE,'1020','DIRECCION31');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE32','CONSUMIDOR32','1-22',SYSDATE,'1021','DIRECCION32');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE33','CONSUMIDOR33','1-23',SYSDATE,'1022','DIRECCION33');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE34','CONSUMIDOR34','1-24',SYSDATE,'1023','DIRECCION34');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE35','CONSUMIDOR35','1-25',SYSDATE,'1024','DIRECCION35');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE36','CONSUMIDOR36','1-26',SYSDATE,'1025','DIRECCION36');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE37','CONSUMIDOR37','1-27',SYSDATE,'1026','DIRECCION37');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE38','CONSUMIDOR38','1-28',SYSDATE,'1027','DIRECCION38');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE39','CONSUMIDOR39','1-29',SYSDATE,'1028','DIRECCION39');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE40','CONSUMIDOR40','1-30',SYSDATE,'1029','DIRECCION40');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE41','CONSUMIDOR41','1-31',SYSDATE,'1030','DIRECCION41');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE42','CONSUMIDOR42','1-32',SYSDATE,'1031','DIRECCION42');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE43','CONSUMIDOR43','1-33',SYSDATE,'1032','DIRECCION43');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE44','CONSUMIDOR44','1-34',SYSDATE,'1033','DIRECCION44');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE45','CONSUMIDOR45','1-35',SYSDATE,'1034','DIRECCION45');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE46','CONSUMIDOR46','1-36',SYSDATE,'1035','DIRECCION46');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE47','CONSUMIDOR47','1-37',SYSDATE,'1036','DIRECCION47');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE48','CONSUMIDOR48','1-38',SYSDATE,'1037','DIRECCION48');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE49','CONSUMIDOR49','1-39',SYSDATE,'1038','DIRECCION49');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE50','CONSUMIDOR50','1-40',SYSDATE,'1039','DIRECCION50');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE51','CONSUMIDOR51','1-41',SYSDATE,'1040','DIRECCION51');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE52','CONSUMIDOR52','1-42',SYSDATE,'1041','DIRECCION52');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE53','CONSUMIDOR53','1-43',SYSDATE,'1042','DIRECCION53');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE54','CONSUMIDOR54','1-44',SYSDATE,'1043','DIRECCION54');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE55','CONSUMIDOR55','1-45',SYSDATE,'1044','DIRECCION55');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE56','CONSUMIDOR56','1-46',SYSDATE,'1045','DIRECCION56');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE57','CONSUMIDOR57','1-47',SYSDATE,'1046','DIRECCION57');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE58','CONSUMIDOR58','1-48',SYSDATE,'1047','DIRECCION58');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE59','CONSUMIDOR59','1-49',SYSDATE,'1048','DIRECCION59');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE60','CONSUMIDOR60','1-50',SYSDATE,'1049','DIRECCION60');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE61','CONSUMIDOR61','1-51',SYSDATE,'1050','DIRECCION61');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE62','CONSUMIDOR62','1-52',SYSDATE,'1051','DIRECCION62');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE63','CONSUMIDOR63','1-53',SYSDATE,'1052','DIRECCION63');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE64','CONSUMIDOR64','1-54',SYSDATE,'1053','DIRECCION64');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE65','CONSUMIDOR65','1-55',SYSDATE,'1054','DIRECCION65');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE66','CONSUMIDOR66','1-56',SYSDATE,'1055','DIRECCION66');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE67','CONSUMIDOR67','1-57',SYSDATE,'1056','DIRECCION67');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE68','CONSUMIDOR68','1-58',SYSDATE,'1057','DIRECCION68');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE69','CONSUMIDOR69','1-59',SYSDATE,'1058','DIRECCION69');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE70','CONSUMIDOR70','1-60',SYSDATE,'1059','DIRECCION70');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE71','CONSUMIDOR71','1-61',SYSDATE,'1060','DIRECCION71');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE72','CONSUMIDOR72','1-62',SYSDATE,'1061','DIRECCION72');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE73','CONSUMIDOR73','1-63',SYSDATE,'1062','DIRECCION73');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE74','CONSUMIDOR74','1-64',SYSDATE,'1063','DIRECCION74');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE75','CONSUMIDOR75','1-65',SYSDATE,'1064','DIRECCION75');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE76','CONSUMIDOR76','1-66',SYSDATE,'1065','DIRECCION76');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE77','CONSUMIDOR77','1-67',SYSDATE,'1066','DIRECCION77');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE78','CONSUMIDOR78','1-68',SYSDATE,'1067','DIRECCION78');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE79','CONSUMIDOR79','1-69',SYSDATE,'1068','DIRECCION79');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE80','CONSUMIDOR80','1-70',SYSDATE,'1069','DIRECCION80');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE81','CONSUMIDOR81','1-71',SYSDATE,'1070','DIRECCION81');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE82','CONSUMIDOR82','1-72',SYSDATE,'1071','DIRECCION82');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE83','CONSUMIDOR83','1-73',SYSDATE,'1072','DIRECCION83');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE84','CONSUMIDOR84','1-74',SYSDATE,'1073','DIRECCION84');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE85','CONSUMIDOR85','1-75',SYSDATE,'1074','DIRECCION85');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE86','CONSUMIDOR86','1-76',SYSDATE,'1075','DIRECCION86');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE87','CONSUMIDOR87','1-77',SYSDATE,'1076','DIRECCION87');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE88','CONSUMIDOR88','1-78',SYSDATE,'1077','DIRECCION88');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE89','CONSUMIDOR89','1-79',SYSDATE,'1078','DIRECCION89');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE90','CONSUMIDOR90','1-80',SYSDATE,'1079','DIRECCION90');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE91','CONSUMIDOR91','1-81',SYSDATE,'1080','DIRECCION91');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE92','CONSUMIDOR92','1-82',SYSDATE,'1081','DIRECCION92');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE93','CONSUMIDOR93','1-83',SYSDATE,'1082','DIRECCION93');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE94','CONSUMIDOR94','1-84',SYSDATE,'1083','DIRECCION94');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE95','CONSUMIDOR95','1-85',SYSDATE,'1084','DIRECCION95');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE96','CONSUMIDOR96','1-86',SYSDATE,'1085','DIRECCION96');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE97','CONSUMIDOR97','1-87',SYSDATE,'1086','DIRECCION97');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE98','CONSUMIDOR98','1-88',SYSDATE,'1087','DIRECCION98');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE99','CONSUMIDOR99','1-89',SYSDATE,'1088','DIRECCION99');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE100','CONSUMIDOR100','1-90',SYSDATE,'1089','DIRECCION100');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE101','CONSUMIDOR101','1-91',SYSDATE,'1090','DIRECCION101');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE102','CONSUMIDOR102','1-92',SYSDATE,'1091','DIRECCION102');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE103','CONSUMIDOR103','1-93',SYSDATE,'1092','DIRECCION103');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE104','CONSUMIDOR104','1-94',SYSDATE,'1093','DIRECCION104');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE105','CONSUMIDOR105','1-95',SYSDATE,'1094','DIRECCION105');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE106','CONSUMIDOR106','1-96',SYSDATE,'1095','DIRECCION106');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE107','CONSUMIDOR107','1-97',SYSDATE,'1096','DIRECCION107');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE108','CONSUMIDOR108','1-98',SYSDATE,'1097','DIRECCION108');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE109','CONSUMIDOR109','1-99',SYSDATE,'1098','DIRECCION109');
INSERT INTO CLIENTE (NOMBRES, APELLIDOS, NIT, FECHA_CREACION,TELEFONO,DIRECCION) VALUES('CLIENTE110','CONSUMIDOR110','1-100',SYSDATE,'1099','DIRECCION110');
/
COMMIT;


/*TRIGGER PARA PODER INSERTAR DATOS EN LA TABLA BITACORA_PRODUCTO*/
CREATE OR REPLACE TRIGGER AIUD_PRODUCTO
AFTER INSERT OR UPDATE OR DELETE ON PRODUCTO
FOR EACH ROW
BEGIN
IF INSERTING THEN
    INSERT INTO BITACORA_PRODUCTO(COD_PRODUCTO,FECHA_MOVIMIENTO,USUARIO_RESPONSABLE,COD_TIPO_TRANSACCION)
    VALUES(:NEW.COD_PRODUCTO,SYSDATE,1,1);
END IF;
IF UPDATING ('NOMBRE') THEN
    INSERT INTO BITACORA_PRODUCTO(COD_PRODUCTO,FECHA_MOVIMIENTO,VALOR_ANTERIOR,VALOR_NUEVO,
    USUARIO_RESPONSABLE,ID_CAMPO_AFECTADO,COD_TIPO_TRANSACCION)
    VALUES(:NEW.COD_PRODUCTO,SYSDATE,:OLD.NOMBRE,:NEW.NOMBRE,1,1,2);
END IF;

IF UPDATING ('DESCRIPCION') THEN
    INSERT INTO BITACORA_PRODUCTO(COD_PRODUCTO,FECHA_MOVIMIENTO,VALOR_ANTERIOR,VALOR_NUEVO,
    USUARIO_RESPONSABLE,ID_CAMPO_AFECTADO,COD_TIPO_TRANSACCION)
    VALUES(:NEW.COD_PRODUCTO,SYSDATE,:OLD.DESCRIPCION,:NEW.DESCRIPCION,1,2,2);
END IF;

IF UPDATING ('ID_ESTADO_PRODUCTO') THEN
    INSERT INTO BITACORA_PRODUCTO(COD_PRODUCTO,FECHA_MOVIMIENTO,VALOR_ANTERIOR,VALOR_NUEVO,
    USUARIO_RESPONSABLE,ID_CAMPO_AFECTADO,COD_TIPO_TRANSACCION)
    VALUES(:NEW.COD_PRODUCTO,SYSDATE,:OLD.ID_ESTADO_PRODUCTO,:NEW.ID_ESTADO_PRODUCTO,1,3,2);
END IF;

IF UPDATING ('ID_TIPO_PRODUCTO') THEN
    INSERT INTO BITACORA_PRODUCTO(COD_PRODUCTO,FECHA_MOVIMIENTO,VALOR_ANTERIOR,VALOR_NUEVO,
    USUARIO_RESPONSABLE,ID_CAMPO_AFECTADO,COD_TIPO_TRANSACCION)
    VALUES(:NEW.COD_PRODUCTO,SYSDATE,:OLD.ID_TIPO_PRODUCTO,:NEW.ID_TIPO_PRODUCTO,1,4,2);
END IF;

IF UPDATING ('PRECIO_COMPRA') THEN
    INSERT INTO BITACORA_PRODUCTO(COD_PRODUCTO,FECHA_MOVIMIENTO,VALOR_ANTERIOR,VALOR_NUEVO,
    USUARIO_RESPONSABLE,ID_CAMPO_AFECTADO,COD_TIPO_TRANSACCION)
    VALUES(:NEW.COD_PRODUCTO,SYSDATE,:OLD.PRECIO_COMPRA,:NEW.PRECIO_COMPRA,1,5,2);
END IF;

IF UPDATING ('PRECIO_VENTA') THEN
    INSERT INTO BITACORA_PRODUCTO(COD_PRODUCTO,FECHA_MOVIMIENTO,VALOR_ANTERIOR,VALOR_NUEVO,
    USUARIO_RESPONSABLE,ID_CAMPO_AFECTADO,COD_TIPO_TRANSACCION)
    VALUES(:NEW.COD_PRODUCTO,SYSDATE,:OLD.PRECIO_VENTA,:NEW.PRECIO_VENTA,1,6,2);
END IF;

IF UPDATING ('GANANCIA') THEN
    INSERT INTO BITACORA_PRODUCTO(COD_PRODUCTO,FECHA_MOVIMIENTO,VALOR_ANTERIOR,VALOR_NUEVO,
    USUARIO_RESPONSABLE,ID_CAMPO_AFECTADO,COD_TIPO_TRANSACCION)
    VALUES(:NEW.COD_PRODUCTO,SYSDATE,:OLD.GANANCIA,:NEW.GANANCIA,1,7,2);
END IF;


IF UPDATING ('STOCK_MAXIMO') THEN
    INSERT INTO BITACORA_PRODUCTO(COD_PRODUCTO,FECHA_MOVIMIENTO,VALOR_ANTERIOR,VALOR_NUEVO,
    USUARIO_RESPONSABLE,ID_CAMPO_AFECTADO,COD_TIPO_TRANSACCION)
    VALUES(:NEW.COD_PRODUCTO,SYSDATE,:OLD.STOCK_MAXIMO,:NEW.STOCK_MAXIMO,1,8,2);
END IF;


IF UPDATING ('STOCK_MINIMO') THEN
    INSERT INTO BITACORA_PRODUCTO(COD_PRODUCTO,FECHA_MOVIMIENTO,VALOR_ANTERIOR,VALOR_NUEVO,
    USUARIO_RESPONSABLE,ID_CAMPO_AFECTADO,COD_TIPO_TRANSACCION)
    VALUES(:NEW.COD_PRODUCTO,SYSDATE,:OLD.STOCK_MINIMO,:NEW.STOCK_MINIMO,1,9,2);
END IF;

IF UPDATING ('EXISTENCIA') THEN
    INSERT INTO BITACORA_PRODUCTO(COD_PRODUCTO,FECHA_MOVIMIENTO,VALOR_ANTERIOR,VALOR_NUEVO,
    USUARIO_RESPONSABLE,ID_CAMPO_AFECTADO,COD_TIPO_TRANSACCION)
    VALUES(:NEW.COD_PRODUCTO,SYSDATE,:OLD.EXISTENCIA,:NEW.EXISTENCIA,1,10,2);
END IF;

END;
/


/*TABLA TIPO DE PRODUCTOS*/


INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('MEDICINA');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('HIGIENE PERSONAL');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('LÁCTEOS');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('SUEROS');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('PRESERVATIVOS');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('OTROS');
COMMIT;
/
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 7');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 8');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 9');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 10');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 11');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 12');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 13');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 14');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 15');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 16');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 17');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 18');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 19');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 20');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 21');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 22');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 23');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 24');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 25');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 26');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 27');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 28');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 29');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 30');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 31');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 32');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 33');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 34');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 35');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 36');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 37');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 38');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 39');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 40');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 41');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 42');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 43');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 44');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 45');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 46');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 47');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 48');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 49');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 50');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 51');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 52');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 53');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 54');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 55');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 56');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 57');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 58');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 59');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 60');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 61');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 62');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 63');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 64');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 65');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 66');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 67');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 68');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 69');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 70');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 71');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 72');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 73');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 74');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 75');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 76');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 77');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 78');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 79');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 80');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 81');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 82');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 83');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 84');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 85');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 86');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 87');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 88');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 89');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 90');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 91');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 92');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 93');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 94');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 95');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 96');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 97');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 98');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 99');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 100');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 101');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 102');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 103');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 104');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 105');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 106');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 107');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 108');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 109');
INSERT INTO TIPO_PRODUCTO (DESCRIPCION) VALUES('TIPO 110');
/
COMMIT;

/*TABLA TIPO_ESTADO_PRODUCTO*/

INSERT INTO TIPO_ESTADO_PRODUCTO (DESCRIPCION) VALUES('ACTIVO');
INSERT INTO TIPO_ESTADO_PRODUCTO (DESCRIPCION) VALUES('INACTIVO');
INSERT INTO TIPO_ESTADO_PRODUCTO (DESCRIPCION) VALUES('DESCONTINUADO');
INSERT INTO TIPO_ESTADO_PRODUCTO (DESCRIPCION) VALUES('AGOTADO');

/*TABLA TIPO_ESTADO_PEDIDO*/
INSERT INTO TIPO_ESTADO_PEDIDO (DESCRIPCION) VALUES('EN PROCESO');
INSERT INTO TIPO_ESTADO_PEDIDO (DESCRIPCION) VALUES('COMPLETADO');
INSERT INTO TIPO_ESTADO_PEDIDO (DESCRIPCION) VALUES('CANCELADO');
INSERT INTO TIPO_ESTADO_PEDIDO (DESCRIPCION) VALUES('ANULADO');


/*TABLA CAMPO_AFECTADO_PRODUCTO*/
INSERT INTO CAMPO_AFECTADO_PRODUCTO (DESCRIPCION) VALUES('NOMBRE');
INSERT INTO CAMPO_AFECTADO_PRODUCTO (DESCRIPCION) VALUES('DESCRIPCION');
INSERT INTO CAMPO_AFECTADO_PRODUCTO (DESCRIPCION) VALUES('ID_ESTADO_PRODUCTO');
INSERT INTO CAMPO_AFECTADO_PRODUCTO (DESCRIPCION) VALUES('ID_TIPO_PRODUCTO');
INSERT INTO CAMPO_AFECTADO_PRODUCTO (DESCRIPCION) VALUES('PRECIO_COMPRA');
INSERT INTO CAMPO_AFECTADO_PRODUCTO (DESCRIPCION) VALUES('PRECIO_VENTA');
INSERT INTO CAMPO_AFECTADO_PRODUCTO (DESCRIPCION) VALUES('GANANCIA');
INSERT INTO CAMPO_AFECTADO_PRODUCTO (DESCRIPCION) VALUES('STOCK_MAXIMO');
INSERT INTO CAMPO_AFECTADO_PRODUCTO (DESCRIPCION) VALUES('STOCK_MINIMO');
INSERT INTO CAMPO_AFECTADO_PRODUCTO (DESCRIPCION) VALUES('EXISTENCIA');


/*tabla tipo_transaccion_producto*/

insert into tipo_transaccion_producto(descripcion) values('INSERCION');
insert into tipo_transaccion_producto(descripcion) values('ACTUALIZACION');
insert into tipo_transaccion_producto(descripcion) values('BAJA');



/*INSERT EN LA TABLA PRODUCTO*/
INSERT INTO PRODUCTO (NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,
PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO, EXISTENCIA)
VALUES('PRODUCTO 1',1,1,80,130,500,40,150);

INSERT INTO PRODUCTO (NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,
PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO, EXISTENCIA)
VALUES('PRODUCTO 2',1,2,60,75,150,15,90);

INSERT INTO PRODUCTO (NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,
PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO, EXISTENCIA)
VALUES('PRODUCTO 3',1,3,20.85,70.30,700,100,375);

INSERT INTO PRODUCTO (NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,
PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO, EXISTENCIA)
VALUES('PRODUCTO 4',1,4,15,26.50,4000,1000,1253);


INSERT INTO PRODUCTO (NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,
PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO, EXISTENCIA)
VALUES('PRODUCTO 5',1,5,35.50,70,400,85,135);

INSERT INTO PRODUCTO (NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,
PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO, EXISTENCIA)
VALUES('PRODUCTO 6',1,6,5,7.50,70000,1000,2535);

INSERT INTO PRODUCTO (NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,
PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO, EXISTENCIA)
VALUES('PRODUCTO 7',1,1,70,100,450,50,300);

INSERT INTO PRODUCTO (NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,
PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO, EXISTENCIA)
VALUES('PRODUCTO 8',1,1,20,25,5000,2500,3005);

INSERT INTO PRODUCTO (NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,
PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO, EXISTENCIA)
VALUES('PRODUCTO 9',1,2,70,110,600,150,300);

INSERT INTO PRODUCTO (NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO, EXISTENCIA)
VALUES('PRODUCTO 10',1,3,10,20,133,10,20);


INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO11',3,94,20,1294,1727,58,263);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO12',1,99,973,4648,1051,81,635);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO13',1,68,1373,3675,1200,169,811);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO14',1,27,647,3166,1401,55,982);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO15',3,99,835,1699,1956,98,628);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO16',2,4,612,4845,1517,62,859);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO17',3,53,909,2907,1180,23,722);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO18',3,107,1106,4412,1805,1,926);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO19',1,103,1224,4571,1026,146,383);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO20',1,56,782,3845,1460,30,714);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO21',4,71,944,4404,1683,17,650);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO22',3,86,1344,2458,1954,104,816);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO23',2,24,1332,3626,1742,1,619);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO24',2,62,693,2046,1019,54,716);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO25',1,60,1331,4749,1648,46,552);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO26',2,63,796,2832,1980,29,659);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO27',1,26,1277,1926,1023,94,620);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO28',1,93,1390,2700,1208,180,650);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO29',4,97,1409,2793,1106,7,798);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO30',1,81,960,4243,1375,66,551);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO31',4,72,1141,3049,1623,172,439);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO32',3,9,1360,4502,1642,124,960);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO33',2,40,1418,3883,1635,33,725);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO34',3,33,1157,4315,1485,52,625);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO35',2,83,755,1981,1359,166,792);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO36',2,48,959,3664,1606,194,946);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO37',2,37,720,4146,1128,74,943);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO38',2,82,1419,3673,1354,199,208);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO39',2,102,1301,2970,1608,20,783);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO40',3,6,848,2622,1342,60,475);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO41',1,6,1373,4252,1925,188,877);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO42',4,30,829,1706,1199,165,794);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO43',4,10,758,4568,1874,90,763);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO44',4,36,1451,3071,1032,151,700);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO45',2,76,934,2765,1273,150,586);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO46',3,78,1481,4275,1684,152,712);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO47',1,84,525,2211,1796,85,808);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO48',1,70,801,1891,1081,8,591);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO49',1,19,848,3257,1177,199,791);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO50',2,26,791,4801,1037,1,990);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO51',3,24,728,3149,1799,29,859);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO52',3,6,798,4652,1986,93,805);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO53',1,13,1292,4541,1312,102,415);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO54',1,55,1459,3157,1884,133,670);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO55',4,58,1418,3555,1266,87,668);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO56',4,52,531,3597,1536,98,312);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO57',1,20,621,2254,1737,120,234);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO58',1,55,752,1697,1142,127,315);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO59',2,12,632,2473,1145,126,928);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO60',3,11,1465,4293,1393,112,214);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO61',3,98,1080,1992,1248,78,850);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO62',4,95,977,2395,1835,149,741);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO63',2,17,695,1965,1967,62,300);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO64',3,95,1430,2898,1788,143,647);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO65',2,81,681,3915,1433,104,244);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO66',3,108,664,3990,1265,182,345);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO67',3,98,1143,2406,1769,107,840);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO68',1,62,1188,4266,1150,105,230);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO69',3,4,1269,2761,1829,67,987);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO70',4,108,1499,2494,1904,125,209);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO71',2,99,971,4327,1365,161,391);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO72',2,86,798,2883,1816,89,960);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO73',1,36,1230,2559,1842,79,973);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO74',2,11,830,4496,1280,27,251);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO75',4,6,1158,2627,1414,173,467);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO76',3,96,579,3705,1850,58,811);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO77',1,81,1398,3302,1314,2,379);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO78',3,36,1313,2962,1540,156,243);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO79',4,2,1485,2603,1832,139,563);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO80',1,104,688,2586,1394,77,947);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO81',1,45,1266,3701,2000,77,609);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO82',3,9,1164,2284,1918,135,832);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO83',1,101,800,1744,1230,12,631);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO84',3,3,560,1603,1836,89,936);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO85',2,19,885,1646,1852,81,804);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO86',1,29,1013,4727,1208,192,985);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO87',3,12,765,3008,1293,199,553);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO88',4,54,840,1824,1292,82,447);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO89',4,39,1388,2377,1327,54,496);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO90',3,92,820,4326,1638,191,751);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO91',3,54,698,3634,1374,186,391);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO92',4,44,1101,1892,1210,120,898);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO93',3,90,1413,4477,1438,153,241);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO94',2,9,924,3531,1117,81,411);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO95',4,98,758,4267,1440,139,308);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO96',4,10,564,4826,1170,59,657);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO97',3,109,1468,2526,1166,171,278);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO98',1,12,745,3760,1243,191,696);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO99',4,107,771,4178,1860,24,478);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO100',4,16,518,4815,1577,123,801);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO101',4,31,1063,4494,1566,89,356);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO102',4,97,1412,2269,1879,15,510);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO103',1,19,910,2714,1201,128,336);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO104',1,1,851,4375,1271,34,675);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO105',3,92,1307,3855,1163,195,745);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO106',1,44,1341,1967,1992,17,593);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO107',1,15,1070,1851,1411,192,832);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO108',1,108,1333,2971,1702,199,639);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO109',3,50,501,2211,1003,175,838);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO110',1,92,641,4287,1057,11,589);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO111',2,1,930,4314,1442,17,920);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO112',2,60,583,3888,1332,181,476);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO113',2,44,1219,2614,1067,192,754);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO114',2,20,1325,3697,1289,149,782);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO115',2,93,1419,2979,1967,139,483);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO116',4,46,1358,4172,1896,126,751);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO117',4,106,835,2283,1623,86,790);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO118',2,97,1246,2391,1461,186,448);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO119',2,64,1045,4375,1704,115,515);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO120',2,40,815,4964,1700,101,776);
INSERT INTO PRODUCTO(NOMBRE,ID_ESTADO_PRODUCTO,ID_TIPO_PRODUCTO,PRECIO_COMPRA,PRECIO_VENTA,STOCK_MAXIMO,STOCK_MINIMO,EXISTENCIA) VALUES ('PRODUCTO121',4,40,554,1786,1494,70,282);
/
commit;















/*CREAR UN PEDIDO*/
INSERT INTO PEDIDO_VENTA (NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE, FECHA_EMISION)
VALUES('12345678-0',1,1,SYSDATE);


INSERT INTO PEDIDO_VENTA (NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE, FECHA_EMISION)
VALUES ('12345678-1',1,1,SYSDATE);


INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-10',2,1,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-11',2,1,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-12',2,2,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-13',2,1,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-14',2,2,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-15',2,1,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-16',2,1,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-17',2,2,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-18',2,1,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-19',2,3,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-20',2,1,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-21',2,1,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-22',2,1,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-23',2,3,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-24',2,3,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-25',2,3,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-26',2,3,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-27',2,3,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-28',2,3,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-29',2,2,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-30',2,1,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-31',2,1,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-32',2,2,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-33',2,3,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-34',2,2,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-35',2,3,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-36',2,1,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-37',2,1,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-38',2,2,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-39',2,3,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-40',2,1,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-41',2,3,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-42',2,1,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-43',2,2,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-44',2,2,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-45',2,2,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-46',2,2,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-47',2,3,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-48',2,3,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-49',2,3,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-50',2,3,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-51',2,2,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-52',2,1,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-53',2,2,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-54',2,3,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-55',2,1,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-10',2,1,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-11',2,1,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-12',2,1,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-13',2,3,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-14',2,2,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-15',2,2,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-16',2,1,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-17',2,3,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-18',2,1,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-19',2,1,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-20',2,2,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-40',2,3,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-41',2,3,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-42',2,3,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-43',2,1,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-44',2,3,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-45',2,2,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-46',2,2,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-47',2,2,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-48',3,1,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-49',3,2,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-50',3,1,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-56',3,1,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-57',3,3,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-58',4,2,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-59',4,3,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-60',4,3,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-61',4,3,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-62',4,1,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-63',4,3,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-64',4,2,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-65',4,2,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-66',4,3,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-67',4,3,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-68',4,2,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-69',4,2,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-70',4,2,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-71',4,2,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-72',4,3,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-73',4,3,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-74',4,1,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-75',1,2,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-76',1,1,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-77',1,2,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-78',1,2,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-79',1,2,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-80',1,3,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-81',1,1,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-82',1,3,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-83',1,2,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-84',1,2,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-85',1,1,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-86',1,1,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-87',1,2,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-88',1,2,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-89',1,1,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-90',1,1,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-91',1,2,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-92',1,3,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-93',1,3,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-94',1,2,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-95',1,1,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-96',1,1,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-97',1,1,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-98',1,3,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-99',1,1,SYSDATE);
INSERT INTO PEDIDO_VENTA(NIT,ID_ESTADO_PEDIDO,USUARIO_RESPONSABLE,FECHA_EMISION) VALUES('1-100',1,3,SYSDATE);



/*FUNCION PARA EXTRAER EL PRECIO VENTA DE UN PRODUCTO*/

CREATE OR REPLACE FUNCTION EXTRAER_PRECIO_PRODUCTO(ID_PRODUCTO NUMBER)
RETURN NUMBER
IS
PRECIO NUMBER(12,2);
BEGIN
    SELECT PRECIO_VENTA INTO PRECIO FROM PRODUCTO WHERE COD_PRODUCTO=ID_PRODUCTO;
    RETURN PRECIO;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO EXISTE UN PRODUCTO CON ESE CODIGO, VERIFIQUE POR FAVOR');
END EXTRAER_PRECIO_PRODUCTO;



/*FUNCION PARA EXTRAER EL MONTO TOTAL DE LOS ARTICULOS POR CODIGO DE PRODUCTO EN UNA VENTA*/
CREATE OR REPLACE FUNCTION MONTO_TOTAL(COD_PRODUCTO NUMBER,CANTIDAD NUMBER)
RETURN NUMBER
IS 
MONTO_PARCIAL NUMBER(12,2);
MONTO_TOTAL NUMBER(12,2);
BEGIN
    SELECT EXTRAER_PRECIO_PRODUCTO(COD_PRODUCTO)INTO MONTO_PARCIAL FROM DUAL;
    MONTO_TOTAL:=CANTIDAD*MONTO_PARCIAL;
    RETURN MONTO_TOTAL;
END;



/*BLOQUE ANÓNIMO PARA INSERTAR DATOS EN LA TABLA DETALLE_PEDIDO*/
DECLARE
MONTO_PARCIAL NUMBER(12,2);
MONTO_TOTALES NUMBER(12,2);
ID_PRODUCTO NUMBER(15):=10;
ID_PEDIDO NUMBER(15):=4;
CANTIDAD NUMBER(10):=10;
BEGIN
    SELECT EXTRAER_PRECIO_PRODUCTO(ID_PRODUCTO) INTO MONTO_PARCIAL FROM DUAL;
    SELECT MONTO_TOTAL(ID_PRODUCTO,CANTIDAD) INTO MONTO_TOTALES FROM DUAL;
    INSERT INTO DETALLE_PEDIDO VALUES(ID_PEDIDO,ID_PRODUCTO,CANTIDAD,MONTO_PARCIAL,MONTO_TOTALES);
END;









SELECT * FROM PEDIDO_VENTA;
/*VAMOS A CREAR UNA FUNCION PARA SABER EL ESTATUS DE PEDIDO*/

CREATE OR REPLACE FUNCTION ESTATUS_PEDIDO(ID_PEDIDO NUMBER)
RETURN NUMBER
IS 
ESTADO_PEDI NUMBER(6);
BEGIN
SELECT ID_ESTADO_PEDIDO INTO ESTADO_PEDI FROM PEDIDO_VENTA WHERE COD_PEDIDO=ID_PEDIDO;
IF(ESTADO_PEDI>0) THEN
RETURN ESTADO_PEDI;
ELSE 
ESTADO_PEDI:=0;
RETURN ESTADO_PEDI;
END IF;
END ESTATUS_PEDIDO;
/
COMMIT;
SELECT ESTATUS_PEDIDO(300) FROM DUAL;
/*FUNCION PARA VALIDAR QUE EL ID DEL PRODUCTO EXISTE*/
CREATE OR REPLACE FUNCTION EXISTE_PRODUCTO (NUMERO_PRODUCTO NUMBER)
RETURN NUMBER
IS 
ID_PROD NUMBER(9);

BEGIN

    SELECT COUNT(*) INTO ID_PROD FROM PRODUCTO WHERE PRODUCTO.COD_PRODUCTO=NUMERO_PRODUCTO;
    IF(ID_PROD>0) THEN 
        RETURN ID_PROD;
    ELSE 
        RETURN 0;
    END IF;
END EXISTE_PRODUCTO;
/
COMMIT;

/*SABER LA EXISTENCIA DEL PRODUCTO*/
CREATE OR REPLACE FUNCTION EXTRAER_EXISTENCIA_PRODUCTO(ID_PRODUCTO NUMBER)
RETURN NUMBER
IS
CANTIDAD NUMBER(12);
BEGIN
SELECT EXISTENCIA INTO CANTIDAD FROM PRODUCTO WHERE COD_PRODUCTO=ID_PRODUCTO;
RETURN CANTIDAD;
END EXTRAER_EXISTENCIA_PRODUCTO;
/
COMMIT;

/*como regla del negocio solo vamos actualizar existencias cuando el pedido tenga un estado 
compelto o anulado*/

CREATE OR REPLACE TRIGGER BI_DETALLE_PEDIDO
BEFORE INSERT ON DETALLE_PEDIDO 
FOR EACH ROW
DECLARE
/*PARA SABER EL ESTATUS DEL PEDIDO*/
ESTADO_VENTA NUMBER(3);
/*VALIDAR QUE EXISTE EL PRODUCTO*/
EXISTE_PROD NUMBER(9);
/*VALIDAMOS LA EXISTENCIA DEL PRODUCTO*/
HAY_EXISTENCIA NUMBER(9);
BEGIN
    /*PRIMERO VALIDAMOS SI EL CÓDIGO DEL PRODUCTO ES EL CORRECTO, SINO REBOTAMOS TODA LA ORDEN*/
    SELECT EXISTE_PRODUCTO(:NEW.COD_PRODUCTO)INTO EXISTE_PROD FROM DUAL;
    IF(EXISTE_PROD>0)THEN
        SELECT ESTATUS_PEDIDO(:NEW.COD_PEDIDO)INTO ESTADO_VENTA FROM DUAL;
        /*SI EL ESTADO DE LA VENTA COMPLETADA O ANULADA DEBE RESTAR O SUMAR LA EXISTENCIA
        RESPECTIVAMENTE*/
        /*SI LA VENTA ESTÁ COMPLETADA, RESTAR EXISTENCIA*/
        IF(ESTADO_VENTA=2)THEN
            /*VALIDAMOS QUE HAYA EXISTENCIA Y ADEMAS    QUE SEA MAYOR A LA CANTIDAD SOLICITADA, NO PUEDE SER MENOR A 0*/
            SELECT EXTRAER_EXISTENCIA_PRODUCTO(:NEW.COD_PRODUCTO)INTO HAY_EXISTENCIA FROM DUAL;
            IF(HAY_EXISTENCIA>0 AND HAY_EXISTENCIA>=:NEW.CANTIDAD_PROD) THEN
            
                UPDATE PRODUCTO SET EXISTENCIA=EXISTENCIA-:NEW.CANTIDAD_PROD WHERE COD_PRODUCTO=:NEW.COD_PRODUCTO;
            ELSE
                RAISE_APPLICATION_ERROR(-20003,'NO HAY EXISTENCIA DEL PRODUCTO '||:NEW.COD_PRODUCTO||
                ' O ES INSUFICIENTE PARA SATISFACER EL PEDIDO REVISE POR FAVOR');
            END IF;
        /*SI LA VENTA SE ANULA, DEVOLVEMOS LAS EXISTENCIAS AL PRODUCTO*/
        ELSIF(ESTADO_VENTA=4)THEN
            UPDATE PRODUCTO SET EXISTENCIA=EXISTENCIA+:NEW.CANTIDAD_PROD WHERE COD_PRODUCTO=:NEW.COD_PRODUCTO;
        /*SI ESTÁ EN PROCESO O CANCELADA NO OPERAMOS NADA*/
        ELSIF(ESTADO_VENTA=1 OR ESTADO_VENTA=3)THEN
            DBMS_OUTPUT.PUT_LINE('');
        ELSE
        /*NO EXISTE EL NUMERO DE TIPO DE PEDIDO*/
            RAISE_APPLICATION_ERROR(-20002,'NO EXISTE TIPO DE PEDIDO CON EL ID '||ESTADO_VENTA||'    REVISE POR FAVOR');
        END IF;
    ELSE
        RAISE_APPLICATION_ERROR(-20001,'NO EXISTE UN PRODUCTO CON EL ID '||:NEW.COD_PRODUCTO||'    REVISE POR FAVOR');
    END IF;

END AI_DETALLE_PEDIDO;



SELECT * FROM PEDIDO_VENTA;
SELECT * FROM TIPO_ESTADO_PEDIDO;

SELECT * FROM PRODUCTO;
SELECT * FROM DETALLE_PEDIDO;

SELECT * FROM DETALLE_PEDIDO;

/*para hacer una inserción mas sencilla en la última tabla (detalle_pedido)
generé números aleatorios con los numeros del id de los productos,
pedidos que estuvieran dentro de las tablas y la existencia fue al azar
pues los productos la mayoría tenían basta existencia*/

ALTER TABLE DETALLE_PEDIDO MODIFY MONTO_PARCIAL NUMBER(12,2);
ALTER TABLE DETALLE_PEDIDO MODIFY MONTO_TOTAL NUMBER(12,2);
DECLARE
MONTO_PARCIAL NUMBER(12,2);
MONTO_TOTALES NUMBER(12,2);
ID_PRODUCTO NUMBER(15);
ID_PEDIDO NUMBER(15);
CANTIDAD NUMBER(7);
BEGIN
    SELECT ROUND(DBMS_RANDOM.VALUE(1,121),0) INTO ID_PRODUCTO FROM DUAL;
    SELECT ROUND(DBMS_RANDOM.VALUE(3,117),0) INTO ID_PEDIDO FROM DUAL;
    SELECT ROUND(DBMS_RANDOM.VALUE(1,5),0) INTO CANTIDAD FROM DUAL;
    SELECT EXTRAER_PRECIO_PRODUCTO(ID_PRODUCTO) INTO MONTO_PARCIAL FROM DUAL;
    SELECT MONTO_TOTAL(ID_PRODUCTO,CANTIDAD) INTO MONTO_TOTALES FROM DUAL;
    INSERT INTO DETALLE_PEDIDO VALUES(ID_PEDIDO,ID_PRODUCTO,CANTIDAD,MONTO_PARCIAL,MONTO_TOTALES);
END;
COMMIT;


SELECT * FROM DETALLE_PEDIDO;
SELECT  * FROM BITACORA_PRODUCTO;
SELECT * FROM PRODUCTO;
SELECT * FROM PEDIDO_VENTA;











